### ISSUE TITLE
Master ticket for website roadmap

### ISSUE THREAD

**Issue by rasagy** [sotm-asia/sotm-asia-2018-website#28]
Dropping a brain dump of things we’ll need to work on/have worked on along with tentative dates. Feel free to chime in!

- [x] Main website with teaser image + logo — Done
- [x] Sponsorship link with sponsor logo placeholders — Done
- [x] Organizers logo — Done
- [x] Code of Conduct link — Done
- [x] Blog link — Done
- [x] CfP & CfS links — Done
- [x] Venue section with map — April 16 — @rasagy to coordinate this
- [x] Section with more details about SOTM (tracks, themes etc.) — ?
- [x] Recap of SOTM Asia 2017 — @jinalfoflia to coordinate this
- [ ] Registration/Ticket link — ?
- [ ] Close the CfP & CfS — ?
- [ ] Update sponsors list with first set of sponsors — ?
- [ ] Page with venue details + how to reach + nearby hotels/acco + contact details for help — ?
- [ ] Section for Announcements (Deadlines, Keynote speakers announced etc.) — ?
- [ ] Twitter section (show some tweets) — ?
- [ ] Page with Program details — ?
- [ ] Update site with `Thanks for attending` + close registration link
- [ ] Link to Youtube channel for videos — ?

cc @geohacker @jinalfoflia @tridip1931
